services:
  postgres:
    image: postgres:15
    container_name: inventory_app_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - inventory_app_network

volumes:
  db_data:

networks:
  inventory_app_network:
    driver: bridge